# Generated by Django 5.2.17 on 2026-09-30 16:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=32)),
                ('manifest_object_key', models.CharField(max_length=512)),
                ('signature_object_key', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issuer', models.URLField(max_length=512)),
                ('subject', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('issuer', 'subject'), name='account_auth0_identity_uniq'), models.CheckConstraint(condition=models.Q(('issuer', ''), _negated=True), name='account_issuer_nonempty'), models.CheckConstraint(condition=models.Q(('subject', ''), _negated=True), name='account_subject_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=16)),
                ('product_code', models.CharField(max_length=100)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('\\A[A-Z]{3}\\Z', 'Use an ISO 4217-style uppercase code.')])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('suspended', 'Suspended')], default='pending', max_length=16)),
                ('state_version', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=16)),
                ('product_code', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('refunded', 'Refunded'), ('suspended', 'Suspended')], max_length=16)),
                ('state_version', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='core.account')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTransactionBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('provider_transaction_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_binding', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authorized', models.BooleanField()),
                ('denial_reason', models.CharField(blank=True, max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_audits', to='core.account')),
                ('entitlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='download_audits', to='core.entitlement')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_audits', to='core.release')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_commit', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{40}\\Z', 'Use a lowercase Git commit hash.')])),
                ('binary_object_key', models.CharField(max_length=512)),
                ('binary_sha256', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a lowercase SHA-256 hex digest.')])),
                ('source_public_url', models.URLField(max_length=1024)),
                ('license_public_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application_commit', 'binary_sha256'), name='release_artifact_identity_uniq'), models.CheckConstraint(condition=models.Q(('application_commit__regex', '^[0-9a-f]{40}$')), name='release_commit_format'), models.CheckConstraint(condition=models.Q(('binary_sha256__regex', '^[0-9a-f]{64}$')), name='release_digest_format')],
            },
        ),
        migrations.AddField(
            model_name='release',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.releaseartifact'),
        ),
        migrations.CreateModel(
            name='SupportSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('customer_status', models.CharField(default='received', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_submissions', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='JiraOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command_kind', models.CharField(max_length=32)),
                ('sanitized_payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jira_commands', to='core.supportsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='JiraMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jira_project_key', models.CharField(max_length=32)),
                ('jira_issue_id', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='jira_mapping', to='core.supportsubmission')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedEventInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('development', 'Development'), ('staging', 'Staging'), ('production', 'Production')], max_length=16)),
                ('provider', models.CharField(max_length=32)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('payload_digest', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\A[0-9a-f]{64}\\Z', 'Use a lowercase SHA-256 hex digest.')])),
                ('normalized_payload', models.JSONField(default=dict)),
                ('signature_verified_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_state', models.CharField(choices=[('received', 'Received'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='received', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('environment', 'provider', 'provider_event_id'), name='verified_event_env_ref_uniq'), models.CheckConstraint(condition=models.Q(('provider_event_id', ''), _negated=True), name='verified_event_ref_nonempty'), models.CheckConstraint(condition=models.Q(('payload_digest__regex', '^[0-9a-f]{64}$')), name='verified_event_digest_format'), models.CheckConstraint(condition=models.Q(('environment__in', ['development', 'staging', 'production'])), name='verified_event_environment_valid')],
            },
        ),
        migrations.CreateModel(
            name='EntitlementEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effect_kind', models.CharField(max_length=32)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(choices=[('active', 'Active'), ('refunded', 'Refunded'), ('suspended', 'Suspended')], max_length=16)),
                ('resulting_version', models.PositiveBigIntegerField()),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effects', to='core.entitlement')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlement_effects', to='core.verifiedeventinbox')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_kind', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.UUIDField()),
                ('details', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.account')),
                ('source_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='core.verifiedeventinbox')),
            ],
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('product_code', ''), _negated=True), name='order_product_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('currency__regex', '^[A-Z]{3}$')), name='order_currency_format'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('environment__in', ['development', 'staging', 'production'])), name='order_environment_valid'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(condition=models.Q(('state_version__gte', 1)), name='entitlement_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='entitlement',
            constraint=models.CheckConstraint(condition=models.Q(('environment__in', ['development', 'staging', 'production'])), name='entitlement_environment_valid'),
        ),
        migrations.AddConstraint(
            model_name='providertransactionbinding',
            constraint=models.UniqueConstraint(fields=('environment', 'provider', 'provider_transaction_id'), name='provider_transaction_env_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='providertransactionbinding',
            constraint=models.CheckConstraint(condition=models.Q(('provider', ''), _negated=True), name='provider_binding_provider_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providertransactionbinding',
            constraint=models.CheckConstraint(condition=models.Q(('provider_transaction_id', ''), _negated=True), name='provider_binding_transaction_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='providertransactionbinding',
            constraint=models.CheckConstraint(condition=models.Q(('environment__in', ['development', 'staging', 'production'])), name='provider_binding_environment_valid'),
        ),
        migrations.AddConstraint(
            model_name='downloadaudit',
            constraint=models.CheckConstraint(condition=models.Q(('authorized', False), ('entitlement__isnull', False), _connector='OR'), name='authorized_download_has_entitlement'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('channel', 'version'), name='release_channel_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='entitlementeffect',
            constraint=models.UniqueConstraint(fields=('event', 'effect_kind'), name='entitlement_event_effect_uniq'),
        ),
        migrations.AddConstraint(
            model_name='entitlementeffect',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_version__gte', 1)), name='effect_version_positive'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['object_type', 'object_id'], name='audit_object_idx'),
        ),
    ]
