[platformio]
src_dir = .

[env:esp32dev]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/ttlappalainen/NMEA2000.git#5b7b9fc3ccc18e30ebfba92da6486cffc6251595
build_src_filter = +<autopilotcontroller.ino.cpp> +<src/>
build_flags = -Iinclude -Wall -Wextra
