# Generated by Django 5.2.17 on 2026-09-30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="OidcAuthorizationAttempt",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("state_digest", models.CharField(max_length=64, unique=True)),
                ("session_key_digest", models.CharField(max_length=64)),
                ("nonce", models.CharField(max_length=255)),
                ("code_verifier", models.CharField(max_length=255)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["expires_at"], name="oidc_attempt_expiry_idx")],
            },
        ),
    ]
