#!/usr/bin/env python3
"""Deterministic crop/resize of SCRUM-89 attachment 10000; no redrawn artwork.

Run with Pillow 12.3.0. Committed outputs let normal product builds use only
Python's standard library to verify provenance with verify-skager-brand.py.
"""
import argparse
import hashlib
import io
import json
from pathlib import Path
import PIL
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'resources/branding'
SOURCE_SHA256 = 'dce92b90a8657d045403cf4508d8220cb0306e6a251d58fbf40e6084ea3ee4ee'
WORDMARK_CROP = (384, 440, 1064, 654)
ICON_CROP = (355, 177, 1091, 913)
SIZES = (16, 20, 24, 32, 40, 48, 64, 128, 256)


def generate():
    if PIL.__version__ != '12.3.0':
        raise SystemExit('Use Pillow 12.3.0 to reproduce the reviewed asset bytes')
    source = (ASSETS / 'skager-wordmark-approved.png').read_bytes()
    if hashlib.sha256(source).hexdigest() != SOURCE_SHA256:
        raise SystemExit('Approved source hash mismatch; refusing unapproved artwork')
    original = Image.open(io.BytesIO(source)).convert('RGB')
    if original.size != (1447, 1087):
        raise SystemExit('Approved source dimensions changed')
    wordmark = io.BytesIO()
    original.crop(WORDMARK_CROP).save(wordmark, format='PNG', compress_level=9)
    icon = io.BytesIO()
    original.crop(ICON_CROP).resize((256, 256), Image.Resampling.LANCZOS).convert('RGBA').save(
        icon, format='ICO', sizes=[(s, s) for s in SIZES], bitmap_format='bmp')
    png = wordmark.getvalue()
    rows = ['  ' + ', '.join(f'0x{byte:02x}' for byte in png[i:i + 16]) + ','
            for i in range(0, len(png), 16)]
    header = ('// Generated by tools/generate-skager-brand.py; approved artwork provenance in resources/branding.\n'
              '#pragma once\n\nnamespace opennav::application {\n'
              'inline constexpr unsigned char kSkagerWordmarkPng[] = {\n' +
              '\n'.join(rows) + '\n};\n}  // namespace opennav::application\n').encode()
    outputs = {'resources/branding/skager-wordmark.png': png,
               'resources/branding/skager.ico': icon.getvalue(),
               'src/application/SkagerBrandAsset.h': header}
    record = {
        'schema': 1, 'issue': 'SCRUM-89', 'implementationIssue': 'SCRUM-236',
        'attachmentId': '10000',
        'source': 'resources/branding/skager-wordmark-approved.png',
        'sourceSha256': SOURCE_SHA256, 'sourceBytes': len(source),
        'sourceDimensions': list(original.size), 'generator': 'tools/generate-skager-brand.py',
        'pillowVersion': PIL.__version__, 'wordmarkCrop': WORDMARK_CROP,
        'iconCrop': ICON_CROP, 'iconSizes': SIZES,
        'derivation': 'Pixel-exact wordmark crop; square source crop scaled with Lanczos for ICO. No redrawn letters or new symbol.',
        'outputs': {path: hashlib.sha256(data).hexdigest() for path, data in outputs.items()}}
    outputs['resources/branding/provenance.json'] = (json.dumps(record, indent=2) + '\n').encode()
    return outputs


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, data in generate().items():
        target = ROOT / path
        if args.check:
            if not target.is_file() or target.read_bytes() != data:
                raise SystemExit('Generated asset differs: ' + path)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)
    print('SKAGER approved assets ' + ('verified' if args.check else 'generated'))
